import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/toaster';
import { ThirdwebProvider } from 'thirdweb/react';
import { AutoConnect } from 'thirdweb/react';
import { client } from '@/consts/client';
import { ThemeProvider } from 'next-themes';
import { Navbar } from '@/components/shared/Navbar';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'NFT Marketplace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <ThirdwebProvider>
            <AutoConnect client={client} />
            <Navbar />
            {children}
            <Toaster />
          </ThirdwebProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
